/* unicode.h — UTF-8 decoding, the character classes pre-tokenizers use, and NFC.
 *
 * The reference is Hugging Face `tokenizers` (what transformers runs), not a Unicode
 * release: the tables in unicode_data.h are generated by tools/gen_unicode_tables.py,
 * which probes the installed `tokenizers` (its Oniguruma regex classes and its NFC)
 * and refuses to write a table that disagrees with it.
 *
 * Input is any bytes. A byte that does not start a valid UTF-8 sequence decodes to
 * TR_CP_INVALID_BASE + byte, a value above U+10FFFF, and encodes back to that same
 * byte: nothing is lost or replaced. Nothing here allocates except tr_nfc. */
#ifndef TR_UNICODE_H
#define TR_UNICODE_H

#include <stddef.h>
#include <stdint.h>

#define TR_CP_INVALID_BASE 0x110000u

/* Decodes the code point starting at s[0] (len >= 1) into *cp and returns the bytes
 * consumed (1..4). Strict: overlong forms, surrogates (U+D800..DFFF), values above
 * U+10FFFF and truncated sequences are invalid, and then only s[0] is consumed. */
int tr_utf8_decode(const uint8_t *s, size_t len, uint32_t *cp);

/* Writes cp (a scalar value, or TR_CP_INVALID_BASE + byte) to out, which has room
 * for 4 bytes. Returns the bytes written (1..4). */
int tr_utf8_encode(uint32_t cp, uint8_t *out);

/* Mutually exclusive classes, as the reference regex engine sees \p{L}, \p{N}, \s. */
typedef enum {
    TR_UCLASS_OTHER = 0,
    TR_UCLASS_LETTER = 1,   /* \p{L} */
    TR_UCLASS_NUMBER = 2,   /* \p{N} */
    TR_UCLASS_SPACE = 3     /* \s */
} tr_uclass;

/* Class of cp. Invalid-byte values and unassigned code points are OTHER unless
 * the reference says otherwise. */
tr_uclass tr_uclass_of(uint32_t cp);

/* Upper bound of tr_nfc's output for len input bytes (NFC grows UTF-8 at most 3x). */
#define TR_NFC_MAX_LEN(len) (3 * (len))

/* Unicode Normalization Form C of src[0..len), written to dst (room for
 * TR_NFC_MAX_LEN(len) bytes, must not overlap src); *dst_len gets the bytes written.
 * Invalid bytes are copied unchanged and behave as starters that compose with
 * nothing. Returns 0, or -1 if scratch memory could not be allocated (dst is then
 * unspecified). Text with no code point that NFC could change is copied without
 * allocating. */
int tr_nfc(const uint8_t *src, size_t len, uint8_t *dst, size_t *dst_len);

#endif
