/* unicode.c -- UTF-8 decode/encode, the \p{L} \p{N} \s classes, and NFC, as implemented in
 * unicode.h. All lookup data comes from unicode_data.h (generated by
 * tools/gen_unicode_tables.py; do not add code-point tables here by hand). */
#include "unicode.h"
#include "unicode_data.h"

#include <stdlib.h>
#include <string.h>

/* ---- Hangul algorithmic constants (UAX #15); syllables are never stored in tables ------- */

#define TR_HANGUL_SBASE 0xAC00u
#define TR_HANGUL_LBASE 0x1100u
#define TR_HANGUL_VBASE 0x1161u
#define TR_HANGUL_TBASE 0x11A7u
#define TR_HANGUL_LCOUNT 19u
#define TR_HANGUL_VCOUNT 21u
#define TR_HANGUL_TCOUNT 28u
#define TR_HANGUL_NCOUNT (TR_HANGUL_VCOUNT * TR_HANGUL_TCOUNT)
#define TR_HANGUL_SCOUNT (TR_HANGUL_LCOUNT * TR_HANGUL_NCOUNT)

static int tr_is_hangul_syllable(uint32_t cp) {
    return cp >= TR_HANGUL_SBASE && cp < TR_HANGUL_SBASE + TR_HANGUL_SCOUNT;
}

/* ---- UTF-8 --------------------------------------------------------------------------- */

int tr_utf8_decode(const uint8_t *s, size_t len, uint32_t *cp) {
    uint8_t b0 = s[0];

    if (b0 < 0x80) {
        *cp = b0;
        return 1;
    }

    int n;
    uint32_t min_cp, c;
    if ((b0 & 0xE0) == 0xC0) {
        n = 2;
        min_cp = 0x80;
        c = (uint32_t)(b0 & 0x1F);
    } else if ((b0 & 0xF0) == 0xE0) {
        n = 3;
        min_cp = 0x800;
        c = (uint32_t)(b0 & 0x0F);
    } else if ((b0 & 0xF8) == 0xF0) {
        n = 4;
        min_cp = 0x10000;
        c = (uint32_t)(b0 & 0x07);
    } else {
        *cp = TR_CP_INVALID_BASE + b0; /* lone continuation byte or 0xF8..0xFF */
        return 1;
    }

    if ((size_t)n > len) {
        *cp = TR_CP_INVALID_BASE + b0; /* truncated at end of input */
        return 1;
    }
    for (int i = 1; i < n; i++) {
        uint8_t bi = s[i];
        if ((bi & 0xC0) != 0x80) {
            *cp = TR_CP_INVALID_BASE + b0; /* not a continuation byte */
            return 1;
        }
        c = (c << 6) | (uint32_t)(bi & 0x3F);
    }

    if (c < min_cp || c > 0x10FFFFu || (c >= 0xD800u && c <= 0xDFFFu)) {
        *cp = TR_CP_INVALID_BASE + b0; /* overlong, surrogate, or above U+10FFFF */
        return 1;
    }
    *cp = c;
    return n;
}

int tr_utf8_encode(uint32_t cp, uint8_t *out) {
    if (cp >= TR_CP_INVALID_BASE) {
        out[0] = (uint8_t)(cp - TR_CP_INVALID_BASE);
        return 1;
    }
    if (cp < 0x80u) {
        out[0] = (uint8_t)cp;
        return 1;
    }
    if (cp < 0x800u) {
        out[0] = (uint8_t)(0xC0u | (cp >> 6));
        out[1] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 2;
    }
    if (cp < 0x10000u) {
        out[0] = (uint8_t)(0xE0u | (cp >> 12));
        out[1] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        out[2] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 3;
    }
    out[0] = (uint8_t)(0xF0u | (cp >> 18));
    out[1] = (uint8_t)(0x80u | ((cp >> 12) & 0x3Fu));
    out[2] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
    out[3] = (uint8_t)(0x80u | (cp & 0x3Fu));
    return 4;
}

/* ---- \p{L} \p{N} \s classes ------------------------------------------------------------ */

static int tr_uclass_range_cmp(uint32_t cp, const tr_uclass_range *r) {
    if (cp < r->first) return -1;
    if (cp > r->last) return 1;
    return 0;
}

tr_uclass tr_uclass_of(uint32_t cp) {
    if (cp < 128u) return (tr_uclass)TR_UASCII_CLASS[cp];

    size_t lo = 0, hi = TR_UCLASS_RANGES_COUNT;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = tr_uclass_range_cmp(cp, &TR_UCLASS_RANGES[mid]);
        if (c == 0) return (tr_uclass)TR_UCLASS_RANGES[mid].klass;
        if (c < 0) hi = mid;
        else lo = mid + 1;
    }
    return TR_UCLASS_OTHER;
}

/* ---- NFC: table lookups -------------------------------------------------------------- */

static int tr_uccc_range_cmp(uint32_t cp, const tr_uccc_range *r) {
    if (cp < r->first) return -1;
    if (cp > r->last) return 1;
    return 0;
}

/* Canonical combining class; 0 for starters, Hangul jamo/syllables, and anything absent
 * from the table (unassigned code points included). */
static uint8_t tr_uccc_of(uint32_t cp) {
    size_t lo = 0, hi = TR_UCCC_RANGES_COUNT;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = tr_uccc_range_cmp(cp, &TR_UCCC_RANGES[mid]);
        if (c == 0) return TR_UCCC_RANGES[mid].ccc;
        if (c < 0) hi = mid;
        else lo = mid + 1;
    }
    return 0;
}

/* Binary search for cp's decomposition table entry; NULL if cp does not decompose. */
static const tr_udecomp_entry *tr_udecomp_lookup(uint32_t cp) {
    size_t lo = 0, hi = TR_UDECOMP_ENTRIES_COUNT;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        uint32_t mid_cp = TR_UDECOMP_ENTRIES[mid].cp;
        if (cp == mid_cp) return &TR_UDECOMP_ENTRIES[mid];
        if (cp < mid_cp) hi = mid;
        else lo = mid + 1;
    }
    return NULL;
}

/* Binary search for a composition pair (a, b) -> c, sorted lexicographically by (a, b). */
static int tr_compose_lookup(uint32_t a, uint32_t b, uint32_t *out) {
    size_t lo = 0, hi = TR_UCOMPOSE_PAIRS_COUNT;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        const tr_ucompose_pair *p = &TR_UCOMPOSE_PAIRS[mid];
        if (a == p->a && b == p->b) {
            *out = p->c;
            return 1;
        }
        if (a < p->a || (a == p->a && b < p->b)) hi = mid;
        else lo = mid + 1;
    }
    return 0;
}

/* ---- NFC: decompose ------------------------------------------------------------------- */

typedef struct {
    uint32_t cp;
    uint8_t ccc;
} tr_cp_ccc;

/* Appends the full (already fully recursive, already internally ordered) canonical
 * decomposition of cp to out, advancing *n. out has room for at least TR_NFC_MAX_DECOMP
 * more entries. Hangul syllables decompose algorithmically; anything else not in the table
 * is its own one-element decomposition. */
static void tr_decompose_one(uint32_t cp, tr_cp_ccc *out, size_t *n) {
    if (tr_is_hangul_syllable(cp)) {
        uint32_t s_index = cp - TR_HANGUL_SBASE;
        uint32_t l = TR_HANGUL_LBASE + s_index / TR_HANGUL_NCOUNT;
        uint32_t v = TR_HANGUL_VBASE + (s_index % TR_HANGUL_NCOUNT) / TR_HANGUL_TCOUNT;
        uint32_t t_index = s_index % TR_HANGUL_TCOUNT;
        out[(*n)++] = (tr_cp_ccc){l, 0};
        out[(*n)++] = (tr_cp_ccc){v, 0};
        if (t_index != 0) out[(*n)++] = (tr_cp_ccc){TR_HANGUL_TBASE + t_index, 0};
        return;
    }

    const tr_udecomp_entry *e = tr_udecomp_lookup(cp);
    if (e != NULL) {
        for (uint8_t i = 0; i < e->len; i++) {
            uint32_t d = TR_UDECOMP_DATA[e->offset + i];
            out[(*n)++] = (tr_cp_ccc){d, tr_uccc_of(d)};
        }
        return;
    }

    out[(*n)++] = (tr_cp_ccc){cp, tr_uccc_of(cp)};
}

/* ---- NFC: canonical ordering (stable, O(k log k) per run) ----------------------------- */

/* Stable merge sort of arr[lo, hi) by ccc, using scratch[lo, hi) as temporary space. */
static void tr_ccc_sort(tr_cp_ccc *arr, tr_cp_ccc *scratch, size_t lo, size_t hi) {
    size_t n = hi - lo;
    if (n < 2) return;
    size_t mid = lo + n / 2;
    tr_ccc_sort(arr, scratch, lo, mid);
    tr_ccc_sort(arr, scratch, mid, hi);

    size_t i = lo, j = mid, k = lo;
    while (i < mid && j < hi) {
        if (arr[i].ccc <= arr[j].ccc) scratch[k++] = arr[i++];
        else scratch[k++] = arr[j++];
    }
    while (i < mid) scratch[k++] = arr[i++];
    while (j < hi) scratch[k++] = arr[j++];
    for (k = lo; k < hi; k++) arr[k] = scratch[k];
}

static void tr_canonical_order(tr_cp_ccc *arr, tr_cp_ccc *scratch, size_t n) {
    size_t i = 0;
    while (i < n) {
        if (arr[i].ccc == 0) {
            i++;
            continue;
        }
        size_t j = i;
        while (j < n && arr[j].ccc != 0) j++;
        tr_ccc_sort(arr, scratch, i, j);
        i = j;
    }
}

/* ---- NFC: compose (UAX #15 canonical composition algorithm) --------------------------- */

/* Hangul L+V -> LV and LV+T -> LVT; NULL (0) otherwise means "look up the general table". */
static int tr_try_compose(uint32_t starter, uint32_t ch, uint32_t *out) {
    if (starter >= TR_HANGUL_LBASE && starter < TR_HANGUL_LBASE + TR_HANGUL_LCOUNT &&
        ch >= TR_HANGUL_VBASE && ch < TR_HANGUL_VBASE + TR_HANGUL_VCOUNT) {
        uint32_t l_index = starter - TR_HANGUL_LBASE;
        uint32_t v_index = ch - TR_HANGUL_VBASE;
        *out = TR_HANGUL_SBASE + (l_index * TR_HANGUL_VCOUNT + v_index) * TR_HANGUL_TCOUNT;
        return 1;
    }
    if (tr_is_hangul_syllable(starter) && (starter - TR_HANGUL_SBASE) % TR_HANGUL_TCOUNT == 0 &&
        ch > TR_HANGUL_TBASE && ch < TR_HANGUL_TBASE + TR_HANGUL_TCOUNT) {
        *out = starter + (ch - TR_HANGUL_TBASE);
        return 1;
    }
    return tr_compose_lookup(starter, ch, out);
}

/* In-place compaction: arr[0, n) canonically ordered in, composed result in arr[0, return). */
static size_t tr_compose_inplace(tr_cp_ccc *arr, size_t n) {
    size_t starter_index = (size_t)-1; /* no starter established yet */
    int last_class = -1;               /* ccc of the last kept, non-absorbed mark since it */
    size_t write = 0;

    for (size_t read = 0; read < n; read++) {
        uint32_t cp = arr[read].cp;
        int ccc = arr[read].ccc;
        uint32_t composite = 0;
        int composed = 0;

        if (starter_index != (size_t)-1 && last_class < ccc) {
            composed = tr_try_compose(arr[starter_index].cp, cp, &composite);
        }
        if (composed) {
            arr[starter_index].cp = composite; /* ccc of the starter stays 0 */
        } else {
            arr[write] = arr[read];
            if (ccc == 0) {
                starter_index = write;
                last_class = -1;
            } else {
                last_class = ccc;
            }
            write++;
        }
    }
    return write;
}

/* ---- tr_nfc --------------------------------------------------------------------------- */

/* True if src[0, len) needs no work: every scalar value is below the safe threshold, and
 * every invalid byte is left as-is (it can compose with nothing). */
static int tr_nfc_fast_path_ok(const uint8_t *src, size_t len) {
    size_t i = 0;
    while (i < len) {
        uint32_t cp;
        int n = tr_utf8_decode(src + i, len - i, &cp);
        if (cp < TR_CP_INVALID_BASE && cp >= TR_NFC_SAFE_THRESHOLD) return 0;
        i += (size_t)n;
    }
    return 1;
}

/* a * b as size_t, or 0 (via *ok = 0) on overflow. */
static size_t tr_mul_checked(size_t a, size_t b, int *ok) {
    if (a != 0 && b > (size_t)-1 / a) {
        *ok = 0;
        return 0;
    }
    *ok = 1;
    return a * b;
}

static int tr_nfc_slow(const uint8_t *src, size_t len, uint8_t *dst, size_t *dst_len) {
    int ok;

    size_t src_cap = tr_mul_checked(len, sizeof(uint32_t), &ok);
    if (!ok) return -1;
    uint32_t *src_cps = len ? malloc(src_cap) : NULL;
    if (len && src_cps == NULL) return -1;

    size_t n_src = 0;
    for (size_t i = 0; i < len;) {
        uint32_t cp;
        int n = tr_utf8_decode(src + i, len - i, &cp);
        src_cps[n_src++] = cp;
        i += (size_t)n;
    }

    size_t decomp_cap_n = tr_mul_checked(n_src, TR_NFC_MAX_DECOMP, &ok);
    if (!ok) { free(src_cps); return -1; }
    size_t decomp_cap_bytes = tr_mul_checked(decomp_cap_n, sizeof(tr_cp_ccc), &ok);
    if (!ok) { free(src_cps); return -1; }
    tr_cp_ccc *decomp = decomp_cap_n ? malloc(decomp_cap_bytes) : NULL;
    if (decomp_cap_n && decomp == NULL) { free(src_cps); return -1; }

    size_t n_decomp = 0;
    for (size_t i = 0; i < n_src; i++) {
        uint32_t cp = src_cps[i];
        if (cp >= TR_CP_INVALID_BASE) {
            decomp[n_decomp++] = (tr_cp_ccc){cp, 0}; /* invalid bytes never decompose */
        } else {
            tr_decompose_one(cp, decomp, &n_decomp);
        }
    }
    free(src_cps);

    size_t scratch_bytes = tr_mul_checked(n_decomp, sizeof(tr_cp_ccc), &ok);
    if (!ok) { free(decomp); return -1; }
    tr_cp_ccc *scratch = n_decomp ? malloc(scratch_bytes) : NULL;
    if (n_decomp && scratch == NULL) { free(decomp); return -1; }

    tr_canonical_order(decomp, scratch, n_decomp);
    free(scratch);

    size_t n_composed = tr_compose_inplace(decomp, n_decomp);

    size_t written = 0;
    for (size_t i = 0; i < n_composed; i++) {
        written += (size_t)tr_utf8_encode(decomp[i].cp, dst + written);
    }
    free(decomp);

    *dst_len = written;
    return 0;
}

int tr_nfc(const uint8_t *src, size_t len, uint8_t *dst, size_t *dst_len) {
    if (tr_nfc_fast_path_ok(src, len)) {
        if (len) memcpy(dst, src, len);
        *dst_len = len;
        return 0;
    }
    return tr_nfc_slow(src, len, dst, dst_len);
}
