/* expf_table.h — GENERATED by tools/gen_expf_table.py (mpmath 1.3.0, 200 bits). Do not edit:
 * change the script and run it again; tools/lint.py compares this file with what it writes.
 * The constants of tr_expf (expf.c); what each one is, and why, is said there and in the script. */
#ifndef TR_EXPF_TABLE_H
#define TR_EXPF_TABLE_H

#include <stdint.h>

#define TR_EXPF_INV_LN2_64 0x1.71547652b82fep+6 /* 64 / ln2 */
#define TR_EXPF_LN2_64_HI 0x1.62e42fee00000p-7 /* ln2 / 64, a multiple of 2^-38: k * hi is exact */
#define TR_EXPF_LN2_64_LO 0x1.a39ef35793c76p-39 /* the rest of ln2 / 64 */
#define TR_EXPF_C3 0x1.5555555555555p-3 /* 1/6 */
#define TR_EXPF_C4 0x1.5555555555555p-5 /* 1/24 */
#define TR_EXPF_C5 0x1.1111111111111p-7 /* 1/120 */
#define TR_EXPF_MARGIN 0x1p-50 /* the error the fast path is allowed before it stops being trusted */
#define TR_EXPF_OVERFLOW_X 0x1.62e42e0000000p+6f /* the largest float whose exp is finite */
#define TR_EXPF_UNDERFLOW_X -0x1.a000000000000p+6f /* below it exp(x) < 2^-150 rounds to zero */

/* 2^(j/64), j = 0..63, rounded to nearest */
static const double tr_expf_pow2[64] = {
    0x1.0000000000000p+0, 0x1.02c9a3e778061p+0, 0x1.059b0d3158574p+0, 0x1.0874518759bc8p+0,
    0x1.0b5586cf9890fp+0, 0x1.0e3ec32d3d1a2p+0, 0x1.11301d0125b51p+0, 0x1.1429aaea92de0p+0,
    0x1.172b83c7d517bp+0, 0x1.1a35beb6fcb75p+0, 0x1.1d4873168b9aap+0, 0x1.2063b88628cd6p+0,
    0x1.2387a6e756238p+0, 0x1.26b4565e27cddp+0, 0x1.29e9df51fdee1p+0, 0x1.2d285a6e4030bp+0,
    0x1.306fe0a31b715p+0, 0x1.33c08b26416ffp+0, 0x1.371a7373aa9cbp+0, 0x1.3a7db34e59ff7p+0,
    0x1.3dea64c123422p+0, 0x1.4160a21f72e2ap+0, 0x1.44e086061892dp+0, 0x1.486a2b5c13cd0p+0,
    0x1.4bfdad5362a27p+0, 0x1.4f9b2769d2ca7p+0, 0x1.5342b569d4f82p+0, 0x1.56f4736b527dap+0,
    0x1.5ab07dd485429p+0, 0x1.5e76f15ad2148p+0, 0x1.6247eb03a5585p+0, 0x1.6623882552225p+0,
    0x1.6a09e667f3bcdp+0, 0x1.6dfb23c651a2fp+0, 0x1.71f75e8ec5f74p+0, 0x1.75feb564267c9p+0,
    0x1.7a11473eb0187p+0, 0x1.7e2f336cf4e62p+0, 0x1.82589994cce13p+0, 0x1.868d99b4492edp+0,
    0x1.8ace5422aa0dbp+0, 0x1.8f1ae99157736p+0, 0x1.93737b0cdc5e5p+0, 0x1.97d829fde4e50p+0,
    0x1.9c49182a3f090p+0, 0x1.a0c667b5de565p+0, 0x1.a5503b23e255dp+0, 0x1.a9e6b5579fdbfp+0,
    0x1.ae89f995ad3adp+0, 0x1.b33a2b84f15fbp+0, 0x1.b7f76f2fb5e47p+0, 0x1.bcc1e904bc1d2p+0,
    0x1.c199bdd85529cp+0, 0x1.c67f12e57d14bp+0, 0x1.cb720dcef9069p+0, 0x1.d072d4a07897cp+0,
    0x1.d5818dcfba487p+0, 0x1.da9e603db3285p+0, 0x1.dfc97337b9b5fp+0, 0x1.e502ee78b3ff6p+0,
    0x1.ea4afa2a490dap+0, 0x1.efa1bee615a27p+0, 0x1.f50765b6e4540p+0, 0x1.fa7c1819e90d8p+0,
};

/* The arguments the fast path cannot settle, and exp of each correctly rounded (200 bits):
 * bits of x, bits of the result. tests/bench_expf.c --check proves there is no other. */
#define TR_EXPF_N_EXCEPTIONS 8
static const uint32_t tr_expf_exceptions[8][2] = {
    {0x377eff81u, 0x3f800080u}, /* exp(0x1.fdff020000000p-17) */
    {0x39c6be5bu, 0x3f800c6du}, /* exp(0x1.8d7cb60000000p-12) */
    {0x4001b249u, 0x40f2cd14u}, /* exp(0x1.0364920000000p+1) */
    {0x40315b33u, 0x417fa47du}, /* exp(0x1.62b6660000000p+1) */
    {0xb3000000u, 0x3f800000u}, /* exp(-0x1.0000000000000p-25) */
    {0xbae0e25cu, 0x3f7f8fa7u}, /* exp(-0x1.c1c4b80000000p-10) */
    {0xbbf0edf1u, 0x3f7e1fe9u}, /* exp(-0x1.e1dbe20000000p-8) */
    {0xc16912cdu, 0x34fd331bu}, /* exp(-0x1.d2259a0000000p+3) */
};

#endif
